import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "#1677ff",
                borderRadius: 5,
                colorBgLayout: "#ffffff",
                colorBgContainer: "#ffffff",
                colorText: "#1C252E",
              },
              components: {
                Layout: {},
                Menu: {
                  subMenuItemBg: "transparent",
                  itemSelectedBg: "#ecf6fe",
                  itemHeight: 44,
                  iconSize: 24,
                  colorText: "#637381",
                },
                Tooltip: {
                  colorBgSpotlight: "#1677ff",
                },
                Button: {
                  colorPrimary: "#1C252E",
                  colorPrimaryHover: "#454F5B",
                  colorPrimaryActive: "#6f767e",
                },
                Tabs: {
                  colorBorderSecondary: "transparent",
                  itemColor: "#637381",
                  itemSelectedColor: "#1C252E",
                  itemHoverColor: "#566572",
                  itemActiveColor: "#637381",
                },
                Pagination: {
                  itemActiveBg: "#1C252E",
                  colorPrimaryHover: "#FFFFFF",
                  colorPrimary: "#FFFFFF",
                  borderRadius: 16,
                },
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
